apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cronjob-deployment
  namespace: <YOUR NAMESPACE>
  labels:
    app: demo-cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-cronjob
  template:
    metadata:
      labels:
        app: demo-cronjob
    spec:
      containers:
      - name: demo-cronjob
        image: image-registry.openshift-image-registry.svc:5000/<YOUR NAMESPACE>/<IMAGE STREAM NAME>
        env:
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: cronjob-secret
              key: token
