kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "demo-cronjob-build"
  namespace: "1475a9-test"
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/3rdmike/routercrontab.git"
      ref: "demo"
  output: 
    to:
      kind: ImageStreamTag
      name: "demo-cronjob:latest"
  strategy:
   type: Docker
