kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cronjob-build"
  namespace: "988040-tools"
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/3rdmike/oc-cronjob.git"
      ref: "geocoder"
  output: 
    to:
      kind: ImageStreamTag
      name: "geocoder-cronjob:latest"
  strategy:
   type: Docker
