apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronjob-deployment
  namespace: 988040-tools
  labels:
    app: cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronjob
  template:
    metadata:
      labels:
        app: cronjob
    spec:
      containers:
      - name: cronjob
        image: image-registry.openshift-image-registry.svc:5000/988040-tools/geocoder-cronjob
        env:
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-token-7mzbg
              key: token
