apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-cronjob-build
  namespace: <YOUR NAMESPACE>
spec:
  source: 
    git:
      uri: <YOUR GIT REPO URL e.g. "https://github.com/3rdmike/oc-cronjob.git">
      ref: <YOUR BRANCH e.g. main>
    type: Git
  output: 
    to:
      kind: ImageStreamTag
      name: <IMAGE STREAM NAME>
  strategy:
    type: Docker
