apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cronjob-deployment
  namespace: 1475a9-test
  labels:
    app: demo-cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-cronjob
  template:
    metadata:
      labels:
        app: demo-cronjob
    spec:
      containers:
      - name: demo-cronjob
        image: image-registry.openshift-image-registry.svc:5000/1475a9-test/router-cronjob-test
        env:
        - name: OC_TOKEN
          valueFrom:
            secretKeyRef:
              name: pipeline-token-zcqq4
              key: token
