# define your cronjobs in this file
# the format is very similar to a standard crontab but defined in yaml
# format reference can be found at: https://github.com/gjcarneiro/yacron
jobs:
  - name: demo-job-01
    command:  "/project/script.sh"
    shell: /bin/sh
    schedule: "*/1 * * * *"